name: Flutter Android Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Release APK to GitHub
        uses: actions/upload-release-asset@v1
        with:
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          release_name: Latest Release
